### ISSUE TITLE
Request for come around

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#1]
Als Arbeitskollege möchte ich einen Request for come around bei Anwesenheit stellen können, sodass ich die Person antreffe, wenn ich zum Zimmer gehe

**Comment by FabianWilms** [comment]
Wie soll die Person darüber benachrichtigt werden?

**Comment by darenegade** [comment]
"Anwesenheit die App" und Push-Notification XD

Ohne Anmeldung und/order zweiter Oberfläche wird es schwer

**Comment by darenegade** [comment]
Zur not globale noti über Browser an alle und Bestätigung über einen Button, aber dann kann es jeder machen. Aber dann ist die Person selber schuld, wenn sie umsonst runter kommt. Und ohne das System müsste sie sowieso vorbei kommen und hätte den Aufwand

**Comment by FabianWilms** [comment]
Ich würde es in die Controller GUI packen

**Comment by darenegade** [comment]
Wenn du von Controller sprichst, was meinst du dann genau?

**Comment by FabianWilms** [comment]
Die Oberfläche über die wir unsere eigene Anwesenheit Steuern und die Daten komfortabel bearbeiten können :D da wollte ich ne zweite GUI bauen

**Comment by darenegade** [comment]
Aha....okay dann meinst du die Oberfläche, von der ich oben auch schon geredet hab......dann sind wir ja auf einer Welle :+1:
