### ISSUE TITLE
Kein GIF wenn kein Sound

### ISSUE THREAD

**Issue by FabianWilms** [FabianWilms/anwesenheit#17]
Wenn der Nutzer in der Oberfläche den Sound deaktiviert hat, wird auch kein Gif abgespielt, weil ich ein kleiner Vollidiot bin 😬

**Comment by darenegade** [comment]
Dann macht das Symbol aber kein Sinn mehr, dann müsstest du es "reduced data mode" nennen oder so und das symbol anpassen

**Comment by FabianWilms** [comment]
So ist das aktuelle Verhalten. Ich will eigentlich, dass er **immer** ein GIF abspielt. Ich habe nur aktuell den Code zur Anzeige innerhalb eines `if`-statements was auf den Status des sound-toggles prüft und da ist es natürlich falsch.
Deswegen habe ich es gestern bei mir Zuhause nicht zum laufen gekriegt :joy:

**Comment by darenegade** [comment]
Ach.... Hatte die doppelte Verneinung überlesen

**Comment by FabianWilms** [comment]
Ich hab's auch kacke formuliert :yum:
