### ISSUE TITLE
Automatische Erfassung von Krankheitsstatus

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#2]
Bei einer Mail mit dem Titel Krankmeldung sollte sich der Status entsprechend anpassen und das "Bis" wird aus dem Mail-Inhalt gefiltert.
Hierzu muss man sich nur selber auf CC setzten und ein Service auf dem Standrechner setzt den Status

**Comment by darenegade** [comment]
Dieses Ticket hat nicht direkt mit diesem Repo zu tun, aber kann als Init für ein anderes gesehen werden

**Comment by FabianWilms** [comment]
Wtf? xD Ich bastel noch eine Controller-Anwendung. Das geht damit leichter als so komplexes Zeug

**Comment by darenegade** [comment]
Wenn du krank bist, schaffst du es vielleicht gerade noch so eine Mail zu schicken und mehr nicht.......UND DANN??? :laughing:

**Comment by FabianWilms** [comment]
not wanted
