### ISSUE TITLE
PushNotifier v2

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#24]
Die Schnittstelle hat sich geändert:
https://api.pushnotifier.de/v2/doc/

**Comment by FabianWilms** [comment]
Wollte ich letztens schon umstellen. Problem an der neuen API: man muss den token regelmäßig refreshen. Das ist natürlich iwie unschön :/ und da die V1 noch funktioniert 🤷

**Comment by darenegade** [comment]
Der neue API Token ist doch ein Jahr gültig, zumindest sagt dass das `expires_at` Field beim Login an der API

**Comment by FabianWilms** [comment]
Ich sag ja **regelmäßig** :grinning:

**Comment by FabianWilms** [comment]
1. Ich hab mir gedacht, dass wir doch eigentlich schon alle die gleiche pushnotifier App nutzen können. Müssen uns halt alle mit dem gleichen apitoken authentifizieren. Damit kriegen wir @MrSebastian evtl auch zur Nutzung :stuck_out_tongue:

**Comment by darenegade** [comment]
Du meinst ein Account für alle und dann n Geräte und alle Notifications gehen an alle Geräte?

**Comment by FabianWilms** [comment]
Eine pushnotifier "App" mit API key

Jeder einen Account

Jeder `n` Geräte

**Comment by darenegade** [comment]
Kannst du deine DeviceID mal erneuern? Dann versuch ich dir mal mit meiner App eine Note zu schicken

**Comment by FabianWilms** [comment]
Das bringt dir ja erstmal nichts. Meine device ID ist aktuell, aber mit **meiner** pushnotifier App verknüpft.
Heißt ich brauche deinen api-token oder du meinen um mich/dich mit meinem/deinem Account anzumelden. Dann kriegst du/ich meinen/deinen user-token und mit dem kannst du/ich dann Geräte abrufen und Nachrichten an diese verschicken.

**Comment by darenegade** [comment]
Ich hab doch deinen API Token XD

**Comment by darenegade** [comment]
Um mich mit deinem Account anmelden zu können, brauche ich deine Credentials

**Comment by FabianWilms** [comment]
Ach stimmt der ist ja in firebase :pensive:

Ja dann meld dich doch Mal damit an und Versuch den gleichen zu nutzen. Sollte eigentlich funktionieren

**Comment by darenegade** [comment]
Geht ohne Probleme.......Müssten dann nur das Datenmodell auf einen APIKey + AppName anpassen

**Comment by FabianWilms** [comment]
🤙

darenegade <notifications@github.com> schrieb am So., 11. Feb. 2018, 17:40:

**Comment by darenegade** [comment]
Das einzige Problem ist jetzt nur noch der iron-ajax, da er einen OPTIONS Preflight macht und der von der API nicht unterstützt wird. Hattest du das schon gelöst?

**Comment by FabianWilms** [comment]
Das Problem hatte ich noch nicht 😐 Zur Not schmeiß iron-ajax raus und nutz
`fetch`.

darenegade <notifications@github.com> schrieb am So., 11. Feb. 2018, 17:42:

**Comment by darenegade** [comment]
Ja, dass dachte ich auch. Hätte ja sein können, dass du das schon mal gelöst hattest

**Comment by darenegade** [comment]
fetch macht es leider auch.......fuck

**Comment by darenegade** [comment]
Ich hab dem Kerl mal geschrieben, dass er OPTIONS in seinem Backend einbauen soll 😄
