### ISSUE TITLE
Switch to gfycat

### ISSUE THREAD

**Issue by FabianWilms** [FabianWilms/anwesenheit#27]
Gfycat hat nicht nur Infos bzgl. der Anzahl der Frames eines GIF, sondern auch über die Framerate. Somit kann die Anzeigedauer eines GIF anhand der Länge eben dieses automatisch eingestellt werden!

**Comment by darenegade** [comment]
Was stört dich an der aktuellen Lösung? Die fixe Länge?
Hast du mal darüber nachgedacht die Steuerung über einen EventHandler zu machen?

codepen.io/anon/pen/vdJxZm

**Comment by FabianWilms** [comment]
Welp, ok. Genau so wollte ich es machen. Mein Fehler: Wenn du direkt auf den Link (https://media.giphy.com/media/dzaUX7CAG0Ihi/giphy.mp4) gehst, loopt das GIF trotzdem. Ich habe es daher nicht in einem `<video>`-Tag ausprobiert 😒
