### ISSUE TITLE
Vorraussichtliche nächste Anwesenheit

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#3]
Man sollte Zeiträume von standardmäßiger Anwesenheit setzen können, die bei Abwesenheit angezeigt werden als "Voraussichtlicht nächste Anwesenheit", insofern eine gesetzute Abwesenheit mit Datum nicht später ist

**Comment by FabianWilms** [comment]
Nicht so komplex. Es wird einfach immer die gesamte Übersicht angezeigt, wann man an welchem Tag da ist (Default Anwesenheitszeiten)

**Comment by darenegade** [comment]
Warum komplex? Genau das meinte ich doch, nur das zusätzlich der nächste Zeitpunkt der anwesenheit noch direkt bei der Person angezeigt wird.
