### ISSUE TITLE
RELEASE-TICKET: Anwesenheit 1.34.5 deployn

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#35]
![](https://media.giphy.com/media/10bzDxGkvSvedq/giphy.gif)

**Comment by FabianWilms** [comment]
- [ ] Sicherheitsfreigabr erfolgt
- [ ] Betriebshandbuch befüllt
- [ ] Service-katalog befüllt
- [ ] SLE ausgearbeitet
- [ ] Abgestimmt mit Kunden
- [ ] Abgestimmt mit KV
- [ ] Abgestimmt mit SV
- [ ] Wartungsfenster mit Betroffenen abgestimmt
