### ISSUE TITLE
Status "bis" Design anpassen

### ISSUE THREAD

**Issue by FabianWilms** [FabianWilms/anwesenheit#36]
Die aktuelle Anzeige des "bis einschließlich" mit Kalender-Emoji ist Kacke und nicht eindeutig für den Nutzer in seiner Bedeutung sehr schwer zu interpretieren.

## Temporäre Umsetzung

Kleinerer Text, in Klammern, wie folgt: `(bis einschl. <datum>)`

## Langfristige Umsetzung

1. Option: Countdown bis 00:01 Uhr des Folgetages?
2. Option: ???

**Comment by darenegade** [comment]
Meinst du mit Option 1 einen Countdown anzuzeigen? Da fällt uns sicher was besseres ein. Wir können aber statt dem Countdown eine Überprüfung (z.B. als Function) einbauen, die die Meldung löscht, wenn das Datum erreicht ist.
Ansonsten sollte die temp. Lösung reichen.
In dem Zusammenhang können wir nochmal über die Kartengröße reden. Ich finde es immer blöd, wenn die unterschiedlich groß sind

**Comment by FabianWilms** [comment]
Jap, das meine ich.
Meldung löschen automatisch finde ich eher unnötig und führt nachher zu mehr Problemen.
Wir unterschiedliche Kartengröße finde ich unkritisch. Es sind halt drei unterschiedliche Informationen. Wenn Sebastian in Tele und du nicht da bist, haben die ja auch alle unterschiedliche Farben 😁

**Comment by darenegade** [comment]
Was für Probleme?

**Comment by darenegade** [comment]
Aber Countdown verwirrt mehr, als das was bringt. Nutzer wollen eher wissen, bis wann eine Person abwesend ist, statt wie lange dies noch hin ist.

**Comment by FabianWilms** [comment]
Falsch eingetragen, wird gelöscht -> wollte man gar nicht

Eintrag wird gelöscht, man möchte aber eigentlich ein späteres Datum eintragen -> war auch falsch.

Insbesondere wo das Datum ohnehin rausfliegt sobald du deinen Status änderst. Was will man da automatisch machen? 

Mir geht es hier rein um die Darstellung **wenn** ein Datum gesetzt ist. Das automatische entfernen empfinde ich als unnötigen Aufwand der wenig nutzen hat.

**Comment by FabianWilms** [comment]
@darenegade sehe ich genauso. War auch nur ein Vorschlag, weil mir nix anderes eingefallen ist xD

**Comment by darenegade** [comment]
Das sind aber keine Probleme:
* Falsch eingetragen, wird nicht gelöscht und steht noch da -> Nutzer sehen altes Datum und sind verwirrt
* Eintrag wird nicht gelöscht, man hat noch kein späteres Datum eingetragen -> Nutzer sehen altes Datum und sind verwirrt

Das Datum fliegt erst raus, wenn man sich anmeldet. Wenn ich aber erst am Nachmittag von der Uni komme, steht da noch bis dahin ein Datum drinnen, was unschön ist.

Ich hab auch nicht gesagt, dass es kein Aufwand ist XD
Für unnötig halte ich es aber nicht. Es ist einfach ein kleines Feature. Aber ja, die Priorität ist eher gering

**Comment by FabianWilms** [comment]
Das Datum fliegt auch raus wenn du den Status über den Controller änderst, und dafür ist er ja auch gedacht.

Ich finde einfach zusätzlichen Backend-Code der zeitgesteuert Daten löscht/ändert in dem Fall hier sinnfrei.
Und die Information "krank" mit einem _falschen_ datum ist immer noch mehr wert als der Standard "abwesend".

**Comment by darenegade** [comment]
Man geht ja nicht in den Controller um von "Abwesend bis XX.XX" auf "Abwesend" zu ändern XD

Warum ist die Information mehr Wert wenn da steht "Krank bis gestern". Dafür ist der Controller ja, damit du das Datum wieder anpassen kannst, wenn du länger krank bist.

**Comment by FabianWilms** [comment]
Weil "Krank bis Gestern" heißt, dass derjenige wahrscheinlich immer noch krank ist. Wenn nur abwesend dort steht geht man davon aus, dass derjenige heute wieder kommt.
Natürlich in Kombination mit den regulären Zeiten, aber es hat definitv mehr Informationsgehalt

**Comment by darenegade** [comment]
Kennst du das nicht, dass man weiß, das eine Person bis gestern Krank war und wenn diese dann nicht kommt alle sagen: "Ja, ich weiß auch nicht ob er heute wieder kommt oder was los ist...." Also ich bin sicher, dass die Leute nicht automatisch davon ausgehen, dass eine Person dann noch länger krank ist.


###### Das liebe ich an der Softwareentwicklung......man kann über jeden scheiß diskutieren und alles in frage stellen XD

**Comment by FabianWilms** [comment]
Kennst du das nicht, dass man weiß, das eine Person bis gestern Krank war und sich dann mit einem Kollegen bei einem privaten Projekt in einem mega unnötigen Issue in ~~11~~ 12 Kommentaren über so einen Unsinn diskutiert hat, dass er sich danach in die Klapse hat einweisen lassen? 😆
