### ISSUE TITLE
Datum in Mail

### ISSUE THREAD

**Issue by FabianWilms** [FabianWilms/anwesenheit#39]
@darenegade Findest du das Datum Sinnvoll? Man kann natürlich immer das Versand-Datum prüfen, aber ich dachte mir, dass das die wenigsten machen.
So hat man ganz klar vor Augen, wann derjenige wiedergekommen ist.

Wenn du es als Sinnvoll ansiehst, sollten wir auch hier moment.js einbauen, um die Darstellung des Datums schöner zu machen :D

**Comment by darenegade** [comment]
*motz*......dann müssen wir ja wieder was pflegen.......*motz*.......zusätzliche Abhängigkeit.......*kotz*..ähh....*motz*.......Ist mir eigentlich ziemlich rille, ob mit oder ohne Zeit in der Mail, da, wie du schon sagst, die Zeit der Mail auch da ist, aber wenn in der Mail auch die Zeit steht, dann bitte richtig formatiert
