### ISSUE TITLE
Bug: Request for Come around

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#4]
Wenn man einen Request verschickt hat, dann kann man keinen weiteren mehr schicken.

Es ist gut, dass man die Person nicht zuspammen kann. Aber wenn der Request bearbeitet wurde, dann sollte es wieder möglich sein.

Cookie setzen mit Name? Dann kann man das überprüfen, ob es bearbeitet wurde und brauch den Namen nur einmal eingeben.

**Comment by FabianWilms** [comment]
its a feature!

**Comment by FabianWilms** [comment]
Feature mit Anzeige, wie lange noch geblockt ist, eingebaut.

siehe https://fabianwilms.github.io/anwesenheit/
