### ISSUE TITLE
BUG: Sounds gehen nicht mehr

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#62]

**Comment by MarEliSeg** [comment]
@FabianWilms nachdem die Sounds wieder funktionieren (3580199) ist aufgefallen, dass der Button zum Deaktivieren des Tons keine Auswirkung hat, falls der Ton schon läuft.

Das ist ultra nervig, weil das Lied der Cantina Band ewig dauert und auch mehrfach abgespielt wird.

Das heißt, der Sound muss unterbrochen werden, sobald der Ton vom Nutzer deaktiviert wird (`this.soundEnabled=false`).

**Comment by darenegade** [comment]
In dem Zusammenhang auch gleich die Soundlänge auf 5-10Sec beschränken

**Comment by FabianWilms** [comment]
"OK den gleichen Song nochmal!" 🎺
