### ISSUE TITLE
Sound/Video nur nach Statuschange

### ISSUE THREAD

**Issue by darenegade** [FabianWilms/anwesenheit#65]
Beim Aufrufen der Seite sollten die Sounds und die Videos nicht gleich gespielt werden. Erst wenn sich tatsächlich der Status ändert

**Comment by FabianWilms** [comment]
Du hattest gesagt (Zitat): "ne das ist doch egal. Die Überprüfung brauchen wir nicht" 😂

**Comment by darenegade** [comment]
"Was kümmert mich mein Geschwätz von gestern!" 
Adenauer
