### ISSUE TITLE
Neuer Statuscode "3" für Telearbeit

### ISSUE THREAD

**Issue by FabianWilms** [FabianWilms/anwesenheit#7]

**Comment by darenegade** [comment]
Und mittag? Und Krank? Und Urlaub? Und ........

**Comment by FabianWilms** [comment]
Na das ist alles gleichzusetzen mit ~~krank~~ abwesend

**Comment by FabianWilms** [comment]
Telearbeit ist einen weiteren Status wert, weil man zwar am Arbeitsplatz, aber nicht physikalisch erreichbar ist.

**Comment by darenegade** [comment]
War auch eher ein Scherz. 😉 
Aber wenn du es so argumentierst, dann ist Telearbeit ja weiterhin gleichzusetzen mit "Im Haus unterwegs". Du arbeitest bist aber nicht physikalisch im Büro. Wo ist der Unterschied und was bringt der neue Status für Vorteile? Neue Farbe 😆 
Fand aber die Ampel-Aufteilung gut, da 
Grün -> "Ich kann zum Büro gehen, da er da ist"
Gelb -> "Ich muss ihn versuchen anders zu erreichen, aber er arbeitet"
Rot -> "Derzeit habe ich keine Chance ihn zu erreichen"

(Ich will nur diskutieren, um mich von meiner Uni Arbeit abzuhalten)

**Comment by FabianWilms** [comment]
Ok, Dann will ich dir Mal helfen dich abzuhalten von der Arbeit.
Deswegen wird die Auswahl der Farbe auch wichtig, um die Ampelstruktur und direkte Erkennbarkeit nicht zu schädigen.
Ich finde trotzdem, dass die Erkenntnis eine andere ist. Wenn ich beim kurzen drauf schauen nur sehr "gelb" denke ich: "OK komme ich später wieder."
Bei Telearbeit soll aber mein Impuls sein: "ich rufe ihn schnell an, auftauchen wird er heute nicht mehr."

**Comment by FabianWilms** [comment]
closed with https://github.com/FabianWilms/anwesenheit/commit/3a06d16e8c744c5e635a4177f07b3584b16910ae
